### ISSUE TITLE
Lighthouse error due to missing file

### ISSUE THREAD

**Issue by Kosai106** [mfrachet/cypress-audit#157]
**What does not work?**
I'm attempting to add Lighthouse scores to our E2E job, however as soon as I add the file to our plugins, Cypress throws an error due to a missing file but I can't exactly figure out _why_ this is happening.

```bash
**Message:** Your `pluginsFile` is invalid: `/Users/**/**/end_to_end/cypress/plugins/index.js`

It threw an error when required, check the stack trace below:

**Details:** Error: ENOENT: no such file or directory, open '/Users/**/**/end_to_end/node_modules/lighthouse/report/generator/../../flow-report/assets/standalone-flow-template.html'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/Users/**/**/end_to_end/node_modules/lighthouse/report/generator/flow-report-assets.js:11:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/**/**/end_to_end/node_modules/lighthouse/report/generator/report-assets.js:10:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**How to reproduce?**
add `const { lighthouse, prepareAudit } = require('@cypress-audit/lighthouse');` to `/cypress/plugins/index.js` and run Cypress.

**Expected behavior**
What is to be expected is that the project works without errors.

**Screenshots / Animated Gifs**
![Screenshot 2022-05-30 at 15 16 20](https://user-images.githubusercontent.com/6379824/171000611-5cdbc4a3-a3e7-4aee-bf84-b275b6441a84.png)

**Environment (please complete the following information):**
 - OS: MacOS Monterey `12.3.1`
 - Chrome version: `102`
 - Cypress version: `9.5.2`
 - @cypress-audit/lighthouse version: `1.3.0`

**Any other information that may help fixing the issue?**

**Comment by Kosai106** [comment]
> Can you show your plugin file, please?

Here you go:

```js
const globby = require('globby');
const { rmdir } = require('fs');
// As soon as I remove this line, the error goes away
const { lighthouse, prepareAudit } = require('@cypress-audit/lighthouse');

module.exports = async (on, config) => {
  require('@cypress/code-coverage/task')(on, config);
  config.testFiles = getTestFiles(config);

  if (process.env.ENABLE_TERMINAL_REPORT) {
    require('cypress-terminal-report/src/installLogsPrinter')(on);
  }

  on('before:browser:launch', (browser = {}, launchOptions) => {
    prepareAudit(launchOptions);
    if (browser.name === 'chrome' && browser.isHeadless) {
      launchOptions.args.push('--window-size=1920,1080');
      return launchOptions;
    }
  });

  on('task', {
    lighthouse: lighthouse(),
    async findFiles(mask) {
      if (!mask) {
        throw new Error('Missing a file mask to search');
      }

      const list = await globby(mask);

      if (!list.length) {
        return null;
      }

      return list[0];
    },

    deleteFolder(folderName) {
      return new Promise((resolve, reject) => {
        rmdir(folderName, { maxRetries: 10, recursive: true }, (err) => {
          if (err) {
            console.error(err);

            return reject(err);
          }

          resolve(null);
        });
      });
    },
  });

  config.browsers = config.browsers.filter((browser) => browser.name === 'chrome');
  if (config.env.config) {
    return { ...config, ...config.env.config };
  }
  return config;
};

function getTestFiles(config) {
  const basePath = '../../cypress/integration';
  const team = config.env.team;
  if (/GROW/.test(team)) {
    return [`${basePath}/billing/!(details)*.spec.ts`];
  } else {
    return '**/*.spec.ts';
  }
}
```
